### PR TITLE
Grammar

### PR DESCRIPTION
**Pull request by DovydasNavickas**

### CODE REVIEW

**Comment by ayende** [comment]
Hi,
Do you have CLA with us?

ravendb.net/contributing

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by DovydasNavickas** [comment]
I think I do. Can't remember 100%, but I think I had one signed.

**Comment by ayende** [comment]
I don't have a record of it, could you send us one ?

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811



On Sat, Oct 24, 2015 at 12:22 AM, Dovydas Navickas <notifications@github.com

**Comment by ayende** [comment]
Thanks!

**Pull request merged**
