### PR TITLE
MAS-3 Cost Cutting on the Cloud Article

### PR DESCRIPTION
**Pull request by mateuszbartosik**

### CODE REVIEW

**Comment by topalach** [comment]
image
The "Available figures" text should be in a separate paragraph and link to an external page.

**Comment by topalach** [comment]
A separate paragraph is needed:
image

**Comment by topalach** [comment]
Another separate paragraph is needed:
image

**Comment by topalach** [comment]
Space needed:
image

**Comment by topalach** [comment]
Separate paragraph:
image

**Comment by topalach** [comment]
image
1. Please surround this with `<em></em>`
2. and 3. - please make them bold

**Comment by topalach** [comment]
There is no "pleased" in the source text:
image

**Comment by topalach** [comment]
New paragraph here:
image

**Comment by topalach** [comment]
This is not the content of the source file:
image

**Comment by mateuszbartosik** [comment]
@topalach everything fixed in recent commit.

**Pull request merged**
