### PR TITLE
promote example uses demote endpoint

### PR DESCRIPTION
**Pull request by deenski**

### CODE REVIEW

**Comment by ayende** [comment]
@reebhub We need this for 4.1 / 4.2 as well, no?

**Comment by deenski** [comment]
Hey @ayende while I have you, we get this error back when trying to hit the proper endpoint. Wondering if it's because we don't have a leader?
`{"Url":"/admin/cluster/promote?nodeTag=A","Type":"Raven.Client.Exceptions.Routing.RouteNotFoundException","Message":"There is no handler for path: GET /admin/cluster/promote?nodeTag=A","Error":"Raven.Client.Exceptions.Routing.RouteNotFoundException: There is no handler for path: GET /admin/cluster/promote?nodeTag=A\n   at Raven.Server.Routing.RequestRouter.HandlePath(RequestHandlerContext reqCtx) in C:\\Builds\\RavenDB-Stable-4.1\\41013\\src\\Raven.Server\\Routing\\RequestRouter.cs:line 62\n   at Raven.Server.RavenServerStartup.RequestHandler(HttpContext context) in C:\\Builds\\RavenDB-Stable-4.1\\41013\\src\\Raven.Server\\RavenServerStartup.cs:line 174"}`

**Comment by ayende** [comment]
This need to be a `POST`

**Comment by deenski** [comment]
Is the api supposed to respond to the request? Now that I modified the request to POST I get a 204 no content back, and my node does not seem to be promoted.

**Comment by ayende** [comment]
Yes, on success, this will return 204

**Comment by ppekrol** [comment]
@ayende Changes will be propagated automatically to other versions.

**Pull request merged**
