### PR TITLE
The incremental import commands have the folder in the wrong location

### PR DESCRIPTION
**Pull request by garrmark**
the folder comes before the database flag

### CODE REVIEW

**Comment by fitzchak** [comment]
Hi, 
Do you have a CLA with us?

**Comment by garrmark** [comment]
I'm not sure what that means.  We are a customer (mgarrison@partssource.com
is my usual email) and have purchased licenses.  I thought I'd help out
with fixing your docs.

**Comment by fitzchak** [comment]
See http://ravendb.net/contributing

**Comment by fitzchak** [comment]
Fixed, thanks.

**Pull request closed without merging**
