### PR TITLE
RDoc-521 update indexDefinition propriety

### PR DESCRIPTION
**Pull request by IdanHaim**

### CODE REVIEW

**Comment by arekpalinski** [comment]
That's all? No info about performance enhancement. @ml054 can you have a look?

**Comment by arekpalinski** [comment]
It seems that the warning about `Increased indexing time` on https://ravendb.net/docs/article-page/3.0/Csharp/indexes/querying/suggestions should be updated. I'm not familiar with details however at least provide info that we are faster than in 3.0

**Comment by ayende** [comment]
The difference is that in 3.0 we are generating a dictionary for suggestions per  distance & accuracy pair.
In 3.5, we are able to have a single dictionary for suggestions globally, and apply the distnace & accurancy per query

**Comment by arekpalinski** [comment]
@ayende Just talked to @ml054 about this again and as I understand that changes has nothing to do with performance. Is it correct?

**Comment by ayende** [comment]
It does, because we don't need to create mulitple dictionaries

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by ml054** [comment]
Actually before change we created dictionary with field name as a key: ex. LastName and {Levenstein; 0.4} as value. During query looked for suggestions in folder: FieldName + Distance + Accuracy. If not found we could not return suggestions. 

Right now we use only field name as directory name and can query for any distance + accuracy. 

When comes to comparing performance in both old and new version we can create only single suggestions for field (in old version key was field name so we can't create multiple entries with different distance/accuracy). 

The only change that I can see it fact that right now we can use any distance / accuracy combination when queries - we don't have to choose them during indexing process.

**Comment by ayende** [comment]
Yes, but didn't we create additional dictionaries on the fly if requested
by the query?

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811



On Tue, Aug 9, 2016 at 1:25 PM, Marcin Lewandowski <notifications@github.com

**Comment by ml054** [comment]
I don't think so, we simply read from different fs dictionary. I omit performance improvement related to lack of string concat code (FieldName + Distance + Accuracy).

**Comment by ayende** [comment]
okay

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811



On Tue, Aug 9, 2016 at 1:52 PM, Marcin Lewandowski <notifications@github.com

**Comment by IdanHaim** [comment]
so do we still get high CPU usage when we use it?

**Comment by ml054** [comment]
For me: if it had high cpu it will still have the same.

**Comment by IdanHaim** [comment]
OK so I think this doc update can be merged without any more update

**Comment by arekpalinski** [comment]
Please drop the information about improved suggestions performance from What's new page (include it in this PR)

**Pull request merged**
